[tool.poetry]
name = "bitsea"
version = "0.1.0"
description = ""
authors = ["OGS"]
readme = "README.md"
packages = [
    { include = "bitsea", from="src" },
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^2.0.2"
scipy = "^1.12.0"
matplotlib = ">3.7.5"
netcdf4 = ">1.6.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pre-commit = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
